/*
    Generated by Atomist on 01 07 2016 
*/
package com.jackie.service;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.test.context.web.WebAppConfiguration;
import org.springframework.boot.test.SpringApplicationConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

@RunWith(SpringJUnit4ClassRunner.class)
@SpringApplicationConfiguration(classes = SimpleMonitoredServiceApplication.class)
@WebAppConfiguration
public class SimpleMonitoredServiceApplicationTests {

	@Test
	public void contextLoads() {
	}
}
