/*
    Generated by Atomist on 01 07 2016 
*/
package com.jackie.service;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
@RestController
public class SimpleMonitoredServiceApplication {

	@RequestMapping("/")
    public String home() {
        return this.toString() + " instance saying: Hello Microservice World";
    }

    public static void main(String[] args) {
        SpringApplication.run(SimpleMonitoredServiceApplication.class, args);
    }
}
