/*
    Generated by Atomist on 01 07 2016 
*/
package com.jackie.service;

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/**
* Spring Java configuration file for SimpleMonitoredService.
* Don't even think of using XML.
*/
@Configuration
public class SimpleMonitoredServiceConfiguration {

    // Your beans go here ... 
	// Atomist Bot suggests "maybe use an Atomist project editor to add a sample one?"
}
